# Generated by Django 4.2.16 on 2024-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_alter_user_options_user_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
