# Generated by Django 4.2.16 on 2024-09-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_user_instagram_handle_user_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
