# Generated by Django 4.2.16 on 2024-09-21 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_app', '0005_remove_user_children_child'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Attendee',
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ('-submitted_at',)},
        ),
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
        migrations.AddField(
            model_name='child',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
