# Generated by Django 4.2.16 on 2024-09-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_rename_user_attendee_alter_child_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='qr_app.attendee'),
        ),
    ]
