# Generated by Django 4.2.16 on 2024-09-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0007_alter_child_attendee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'Attendee', 'verbose_name_plural': 'Attendees'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AddField(
            model_name='attendee',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
