# Generated by Django 4.2.16 on 2024-09-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0008_alter_attendee_options_alter_child_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='number_of_children',
        ),
    ]
